import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header19 from "@/component/early/Header19";
import Hero18 from "@/component/early/Hero18";
import BrowserCategory3 from "@/component/early/BrowserCategory3";
import NeedSomething18 from "@/component/early/NeedSomething18";
import CounterInfo1 from "@/component/early/CounterInfo1";
import Testimonials13 from "@/component/early/Testimonials18";
import ForClient from "@/component/early/ForClient";
import HomeLayouts from "@/component/layouts/HomeLayouts";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Blackhards - AI-Powered Game Marketplace | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayouts>
        <div className="body_content">
          <Hero18 />
          <BrowserCategory3 />
          {/* <TrendingService3 /> */}
          {/* <TrendingAuctions1 /> */}

          <NeedSomething18 />
          <CounterInfo1 />
          {/* <HighestRated18 /> */}
          <Testimonials13 />
          <ForClient />
          {/* <OurBlog1 /> */}
        </div>
      </HomeLayouts>
    </>
  );
}
