import Head from "next/head";
import { Inter } from "next/font/google";
import NeedSomething from "@/components/early/NeedSomething18";
import CounterInfo from "@/components/early/CounterInfo1";
import Testimonials from "@/components/early/Testimonials18";
import ForClient from "@/components/early/ForClient";
import HomeLayoutsEarlyAccess from "@/components/layouts/HomeLayoutsEarlyAccess";
import { useAppSelector } from "@/redux/app/hooks";
import { useRouter } from "next/router";
import Hero from "@/components/early/Hero";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter()
  const user = useAppSelector(state => state.auth.user)

  return (
    <>
      <Head>
        <title>Blackhards - AI-Powered Game Marketplace | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayoutsEarlyAccess>
        <div className="body_content">

          <Hero />
          <NeedSomething />
          <CounterInfo />
          <Testimonials />
          <ForClient />
        </div>
      </HomeLayoutsEarlyAccess>
    </>
  );
}
